### ISSUE TITLE
Open fold on search?

### ISSUE THREAD

**Issue by brograhamer** [turigeza/fold-navigator#11]
We use Atom's built-in search, would like to open folds if we search the item (currently it finds it, does not open the fold or it's contents within). 

I know there is the Fold Navigator Search, which is great, but using Atom's built-in is a bit quicker and more natural for us.

**Comment by turigeza** [comment]
While I agree that the built in search does not open the folds (Well it does but in several steps.) is rather annoying.  It however has nothing to do with this plugin but rather with Atom itself. IMO it is a bug in Atom and would be best dealt with at source. 

The folding features this plugin uses are all part of Atom I have not reimplemented anything new. The way this plugin would fold a code is exactly the same how Atom does it and therefor the built in search should be able to open the folds all the way to the matched string. 

I would suggest raising this issue with them. Later on I might even do it myself because I also use the native search for finding strings and find this a pain.

**Comment by brograhamer** [comment]
@turigeza insightful, thank you for a speedy reply and for pointing out a much more obvious issue with Atom's source. I'll see if there's an open issue existing before I point this out. Thank you for a great plugin!

**Comment by brograhamer** [comment]
@turigeza This was actually accepted and patched in the latest beta version. Can be closed.
