### ISSUE TITLE
PSR formatting support

### ISSUE THREAD

**Issue by brograhamer** [turigeza/fold-navigator#12]
In PHP the PSR format is not supported in `fold-navigator`. All you see is curly braces in the navigator using the following format:

```
function someClass()
{
    $content = 'Can we get a fix for this pretty please? You\'re the bomb!';

    return $content;
}
```

**Comment by turigeza** [comment]
Sorry I was away ...

You are right. 

It works as expected it lists the folding point. Which in this case falls on the {
[](url)
Do you think it is an Atom issue ? I mean Atom should fold on the function name instead of the curly braces no ? Mind I bet it would be difficult to convince them to change this behaviour ... 

<img width="656" alt="screen shot 2017-08-28 at 14 35 55" src="https://user-images.githubusercontent.com/9335740/29773667-b52bf006-8bfe-11e7-9d49-607d7cfea0b0.png">

I most likely just bodge it and list the previous row if the row = {

Does that sound ok ?

**Comment by brograhamer** [comment]
No worries at all!

It does work as expected. I think however it can be extended to check for both circumstances.

For `php`, the following should be assessed:

```
function someClass(){ // no space, folds here
function someClass() { // spaced, folds here
```

If it does not meet those conditions it should check the previous line and fold:

```
function someClass()
{ // folds here
```

I think until Atom patches this issue we should look to resolve it. I wrote the Atom team about an issue with folding / search and they actually did patch it rather quickly for the latest Beta release (several ago, I think), so they are 100% willing to look into it if I wrote them about it. 

Do you think that's something Atom should do by default, fold on the previous row is PSR is used? I believe it should. Will send them a ticket if you agree.

Apologies if I'm unclear. Hard to explain technicalities this early. I appreciate your time and willingness to look into this with me!

**Comment by turigeza** [comment]
I think I fix it so it looks to the previous line when certain characters match.

**Comment by brograhamer** [comment]
Wow, speedy! Very nice. Will an update be available shortly? Also, do you think I should write Atom about this issue on a broader scale? Might be worthwhile.

**Comment by turigeza** [comment]
Hopefully that should be it solved if you notice any issues with it let me know.
