### ISSUE TITLE
provide option to activate the plugin by default

### ISSUE THREAD

**Issue by xh3b4sd** [turigeza/fold-navigator#8]
I experienced the plugin is not able to work until the navigator is opened at least once. Currently I do not care about the navigator and I have the following hack in my `init.coffee` to make the plugin work out of the box.

```
atom.packages.onDidActivateInitialPackages ->
  workspaceView = atom.views.getView(atom.workspace);
  atom.commands.dispatch(workspaceView, 'fold-navigator:toggle');
  atom.commands.dispatch(workspaceView, 'fold-navigator:toggle');
```

Is this the right way to do it? Do we maybe want to put this directly into the plugin? When I install a plugin I expect it just to work. So the need of the hack above should not be necessary IMO.

**Comment by turigeza** [comment]
I had a go at making this an option and it was not easy at all so I gave up. I personally do not like to start it with atom. But then I have atom open most of the time. I don't restart it often. 

I tried and and your script doesn't work btw should it ?

I really do not know how to start it if you manage to find the right way to do it please post here :)

I will leave this open you are the second person asking for it. I might have a go at it again but not for while just because the amount of work I have just now.

**Comment by xh3b4sd** [comment]
I updated the description. The snippet there was broken because I played around a bit and copied the wrong version. It works to activate the plugin by calling `fold-navigator:toggle` twice.

**Comment by turigeza** [comment]
This is great by the way. Thank you for that.

**Comment by xh3b4sd** [comment]
Thanks. It is only a little odd to have it in your personal init script. Do you think it would make sense to provide an option for that? I am fine when it is disabled by default.

**Comment by turigeza** [comment]
Yes of course it would make sense. :) It's just not as trivial as you might
think and I didn't manage to do it.

I think if I recall right because the plugin options are not available
until  the plugin loaded :) so I couldn't make it an option of the plugin.

So there is nothing wrong with the idea I think it's nice idea. Just that I
couldn't get it to work.

I added your init script to my atom as well let's see maybe will modify the
plugin to start at startup with atom. But then one doesn't have the option
not to start it. And for some who use atom for quick editing of files and
keeps opening and closing it it can drag the startup process.

Worth an other shot in the meantime I might put your code on the front page
so people know how to if they want to.
Because once you have the code it isn't actually  great deal of work to
open the script and copy paste.

**Comment by turigeza** [comment]
I have linked to this issue in the readme.
