### ISSUE TITLE
not possible to toggle folds separately on configured indentation level

### ISSUE THREAD

**Issue by xh3b4sd** [turigeza/fold-navigator#9]
Coming from vim it was hard to me finding something that is able to provide folding as I am used to it. This plugin misses a small detail to configure. Consider the following vim configuration options.

```
set foldnestmax=1
set foldmethod=indent
```

This folds based on indentation level and only folds everything that is not at the beginning of the line. Would it make sense to add something to achieve this? Currently this is only possible for folding everything in a file. I would like to be able to toggle folds per fold.

**Comment by turigeza** [comment]
I don't quite get it because I do not use vim but is this not a built in Atom feature?

See screenshot.
![screen shot 2016-10-15 at 14 57 09](https://cloud.githubusercontent.com/assets/9335740/19410586/b7bcfa74-92e7-11e6-8cea-2d083061298a.png)

**Comment by xh3b4sd** [comment]
This looks like it will only close the fault. I would like to use this in a keybinding that toggles this behaviour. My current workflow in vim is pressing `ctrl-f` to open/close folds by 1 indentation level.

**Comment by turigeza** [comment]
I am so not familiar with vim I would need to try to see what you mean.

> This looks like it will only close the fault.
> Fold and Unfold = can toggle the current fold.

But you want toggle fold level 1 and only fold level one ?

You can toggle folds at different levels with the commands see screen shot
<img width="643" alt="screen shot 2016-10-15 at 16 49 54" src="https://cloud.githubusercontent.com/assets/9335740/19411325/8c257ef8-92f7-11e6-89f4-5ea12b2d759b.png">

This will only affect the folds at a certain level. It will not try and go beyond the level you are opening closing. So if you have folded the level 3 and you are using command ToggleFoldsLevel1
it will not open the folds at level 3. If that make sense.

And it also seems like it has bug in it ... just notice because I don't often use it. Level 2 is what I use (used to not anymore ) and I think you might be looking for that ?
I think you could achieve the behaviour like  set foldnestmax=1

ON the other hand 
set foldmethod=indent
Looked at it here :
http://vimdoc.sourceforge.net/htmldoc/fold.html#fold-behavior
indent      more indent means a higher fold level

I think this is the default behaviour in Atom

Does any of this help?

**Comment by xh3b4sd** [comment]
> But you want toggle fold level 1 and only fold level one ?

Correct. `foldmethod=indent` is the default for Atom but I am not aware of something like `foldnestmax=1` in conjunction. `ToggleFoldsLevel1` toggles all folds. I want to control the folds separately. Further it only folds one level. I want it to fold every line of the current function block which starts with at least one whitespace. 

Here you see a gif I just made to demonstrate how I work right now. By default all folds are closed. I move between folds using `ctrl-j` (down) and `ctrl-k` (up). This aligns to vim's `j` (down) and `k` (up). When I want to open or close a fold I use `ctrl-f` which toggles only the current fold, and not all. 

![ezgif-2916242232](https://cloud.githubusercontent.com/assets/552769/19411697/a8ac83d2-9306-11e6-8e2e-8df1eb9fd960.gif)

**Comment by turigeza** [comment]
Very nice thank you for that. Just because this makes it obvious what you
are doing.

You can do something similar by limiting the number of folds the plugin
will parse.

It looks like you are not interested in deeper than one fold levels.

So

go to the plugin settings and set the following:

Check - Autofold on open (optional)
Check - Keep code folded
Check - Keep code folded even on shortcuts
Set 1 (maybe 2 but it looks like 1 on your screen shot) - Maximum fold
level navigator will list
Check - Unfold all subfolds

Unfortunately this will still open the folds as you move (I don't know a
way yet to get around that) but it will also close it as you move on. So it
is not quite the same as what you do on the screenshot but might help you.

Also are you using the fuzzy search at all ? I use that all the time.
Sometimes 3 4 letter can take you to the right place. Faster than going
from fold to fold ... just a thought.
​
This is best I can suggest for now : )

<img width="860" alt="screen shot 2016-10-15 at 18 20 27" src="https://cloud.githubusercontent.com/assets/9335740/19412052/065a96c4-9305-11e6-8bf0-c18212c4e421.png">

**Comment by xh3b4sd** [comment]
I was not able to configure the desired behaviour. Instead I wrote my own package. If you like you can give it a shot and give some feedback. Bear with my Atom/Coffeescript skills. Note that I still miss to not fold comments in my package.

**Comment by xh3b4sd** [comment]
I forgot to share the link with you. :D Here you go.

https://atom.io/packages/vim-fold-one
